### ISSUE TITLE
Add hackathons to hacks.json

### ISSUE THREAD

**Issue by geekyd** [geekyd/Event-Buddy#1]
Add major hackathons to hacks.json.

Add the following text to the PR.
`Related Issue : #issuenumber`

**Comment by Dumbaz** [comment]
Does it have to be an US Event or is any country okay?

**Comment by geekyd** [comment]
It can be from anywhere around the world.

**Comment by 00111000** [comment]
Do they have to be future hackaphons or can they be hackaphons in the past?

**Comment by geekyd** [comment]
@00111000 If it is an annual event then it can be from past also.
