### ISSUE TITLE
Add month using moment to homepage

### ISSUE THREAD

**Issue by geekyd** [geekyd/Event-Buddy#18]
![screen shot 2017-10-12 at 3 07 15 pm](https://user-images.githubusercontent.com/12807846/31489758-63363b24-af5f-11e7-8402-a172aec7dcbe.png)

**Comment by chaintng** [comment]
I will take this :)

**Comment by chaintng** [comment]
Please check pull request: https://github.com/geekyd/Event-Buddy/pull/21
