### ISSUE TITLE
Change the header background color & use logo instead of text

### ISSUE THREAD

**Issue by geekyd** [geekyd/Event-Buddy#19]
![screen shot 2017-10-12 at 3 12 38 pm](https://user-images.githubusercontent.com/12807846/31489883-d217b766-af5f-11e7-9165-7e055f976313.png)

To do:
- Change the color of header and render the logo at src/assets/logo.png
- Add a favicon. Use the logo for the favicon

**Comment by georgemickleburgh** [comment]
I will pick it up
