### ISSUE TITLE
Add fork & star buttons to header

### ISSUE THREAD

**Issue by geekyd** [geekyd/Event-Buddy#26]
![screenshot from 2017-10-14 06-46-33](https://user-images.githubusercontent.com/12807846/31571170-72aa7ece-b0ab-11e7-8d07-aa26053a24d6.png)

Add fork & star ob github buttons under the logo. The buttons should be similar to the github buttons.
![screenshot from 2017-10-14 06-48-49](https://user-images.githubusercontent.com/12807846/31571195-c04eb564-b0ab-11e7-9e3a-8a61f4798baf.png)

**Comment by crod93** [comment]
Should these buttons be corresponding to the eventBuddy github repo or ?

**Comment by geekyd** [comment]
@crod93 Please checkout other issues. Thanks :)
