### ISSUE TITLE
Update Readme 

### ISSUE THREAD

**Issue by geekyd** [geekyd/Event-Buddy#43]
ToDo:

- Add logo to readme
- Add screenshots of the application

**Comment by darthgera123** [comment]
Just a clarification, the event buddy logo is the same one as the one on https://event-buddy.herokuapp.com/#/ and we have to put the screenshots of the same

**Comment by darthgera123** [comment]
only #47 and #42 were open as per the labels and they are as well merged

**Comment by geekyd** [comment]
The PR #47 Addresses this issue.

**Comment by udit-001** [comment]
Is this resolved yet or not?
