### ISSUE TITLE
Fix the typo in "Hackatons" in top menu

### ISSUE THREAD

**Issue by udit-001** [geekyd/Event-Buddy#50]
Change "Hackatons" to "Hackathons" in top menu.

![event-buddy herokuapp com- laptop with mdpi screen](https://user-images.githubusercontent.com/23015406/31589161-729b21ac-b21a-11e7-86c3-909f4b89fac6.png)

**Comment by geekyd** [comment]
Check `/src/components/header.vue` for this issue.

**Comment by udit-001** [comment]
Hey, I created a pull request for these changes, kindly review it!

**Comment by gdsrosa** [comment]
it has already been done?

**Comment by geekyd** [comment]
@gdsrosa Yes please check #53
