### ISSUE TITLE
Feature: Add functionality to change the month

### ISSUE THREAD

**Issue by geekyd** [geekyd/Event-Buddy#59]
Currently the events of only current month is listed. Please add functionality to change the month using navigation button.

***Note: Do not implement the previous button when the current month is shown.***

**Comment by gate3** [comment]
What file contains this functionality?

**Comment by scebotari66** [comment]
I can take care of this..

**Comment by geekyd** [comment]
Add the buttons in `header.vue` file

**Comment by mitch3b** [comment]
I'm working on this. I added the buttons and it updates the date. Is this sufficient? Spent some time trying to get the event info to update as well, but looks like there's no connection currently and I have very limited knowledge of Vue

**Comment by geekyd** [comment]
We need to change the month with the navigation buttons. You can use this to learn Vue https://vuejs.org/v2/guide/

**Comment by gsuxlzt** [comment]
If this is not yet implemented, I'd like to have a go at it. I'll make a PR as soon as I'm done.

**Comment by jatempa** [comment]
I want to work on this !

**Comment by geekyd** [comment]
@jatempa Sure, Please go ahead

**Comment by jatempa** [comment]
What is the issue? I mean, I can see a navigation top for change the month, Pleas can you explain me what do you want?

**Comment by geekyd** [comment]
@jatempa You can improve the UI of the buttons & we should not allow user to go beyond 2017 i.e we should only allow user to scroll till `jan 2017`
